# Generated by Django 5.0.2 on 2024-03-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhanwisapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regmodel',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='regmodel',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='regmodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='regmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='regmodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='regmodel',
            name='phno',
        ),
    ]
