# Generated by Django 5.0.2 on 2024-03-20 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhanwisapp', '0002_remove_regmodel_age_remove_regmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regmodel',
            name='country',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='regmodel',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regmodel',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
